apiVersion: v1
kind: Pod
metadata:
  labels:
    entorno: desarrollo
    nombre: mongo
  name: mongo
  namespace: default
spec:
  containers:
  - image: mongo:3.6.2
    name: mongo
    ports:
    - containerPort: 27017
      protocol: TCP