apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        subset: grupo1
        port:
          number: 9080
  - match:
    - uri:
        exact: /producto
    rewrite:
      uri: /productpage
    route:
    - destination:
        host: productpage
        subset: grupo2
        port:
          number: 9080  
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: revisiones
spec:
  hosts:
  - reviews
  http:
  - match:
      # Note that Istio doesn’t have any special, built-in understanding of user identity. This example is enabled by the fact that the productpage service adds a custom end-user header to all outbound HTTP requests to the reviews service.
    - headers:
        end-user:
          exact: egsmartin
    route:
    - destination:
        host: reviews
        subset: v1
    timeout: 0.5s
  - route:
    - destination:
        host: reviews
        subset: v2
      weight: 50
    - destination:
        host: reviews
        subset: v3
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
  - ratings
  http:
  - match:
      # To test the Bookinfo application microservices for resiliency, inject a 7s delay between the reviews:v2 and ratings microservices for user nico. This test will uncover a bug that was intentionally introduced into the Bookinfo app.
    - headers:
        end-user:
          exact: nico
    route:
    - destination:
        host: ratings
        subset: v1
    fault:
      delay:
        percent: 100.0
        fixedDelay: 7s
  - route:
    - destination:
        host: ratings
        subset: v1