apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: jib
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/eugeniogarcia/knative-heroes.git
      revision: master
 
  steps:
  - name: build-and-push
    image: gcr.io/cloud-builders/mvn:latest
    args: ["compile", "jib:build", "-Dimage=docker.io/egsmartin/hello-jib", "-DallowInsecureRegistries=true"]