apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-account
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
data:
  # 'echo -n "egsmartin@gmail.com" | base64'
  username: ZWdzbWFydGluQGdtYWlsLmNvbQ==
  # 'echo -n "Pupa1511" | base64'
  password: UHVwYTE1MTE=